# Venkat Nagappan - Tmux Config
source /usr/share/powerline/bindings/tmux/powerline.conf
tmux_conf_new_pane_retain_current_path=false
tmux_conf_new_window_retain_current_path=false

#set -g default-terminal "xterm-256color"
set -g default-terminal "screen-256color"
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set-option -g default-shell /bin/zsh
set-option -g default-command /bin/zsh

set -g monitor-activity on
set -g visual-activity on

set -g base-index 1
set -g pane-base-index 1
set -g xterm-keys on

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind-key -n F2 new-window
bind-key -n F3 previous-window
bind-key -n F4 next-window
bind-key -n F5 split-window -v
bind-key -n F6 split-window -h
bind-key -n F8 command-prompt -I "#W" "rename-window '%%'"
bind-key -n F7 command-prompt "find-window '%%'"
bind-key -n F10 setw synchronize-panes
bind-key -n F11 resize-pane -Z
bind-key -n F12 kill-pane

bind-key -n S-Left resize-pane -L
bind-key -n S-Right resize-pane -R
bind-key -n S-Up resize-pane -U
bind-key -n S-Down resize-pane -D

set -g status-interval 1
# Set the status bar appearance
#set -g status-left-length 5
#set -g status-right-length 100
#set -g status-justify centre
# Remove extra spaces
#set -g status-left ''
#set -g window-status-separator ''

# Define colors for the status bar
set -g status-bg black
set -g status-fg white
# Customize the left side of the status bar
#set -g status-left '#[bg=black,fg=white] #S'
#set -g status-right "#(uptime -p) "
# Customize the right side of the status bar
set -g status-right '#[bg=black,fg=white] | IP: #(ifconfig enxf6ec6ac62ae2 | grep "inet " | awk "{print \$2}") | MEM: #(free -m | awk "/^Mem:/ {printf \"%.1fGB (%.1fGB)\", \$3/1024, \$2/1024}") | DATE: #(date "+%A, %b %d %I:%M %p")'
set -g status-style fg=white,bg=black
set -g pane-border-style fg=black,bold
set -g pane-active-border-style fg=grey

# You can experiment with different colors for borders to get the appearance of a gap
set -g pane-border-format "#{pane_index}"
#set -g pane-active-border-format "#{pane_index} | #{pane_title}"

# Optionally, you can also increase the padding in panes:
#set -g status-left-length 50
#set -g status-right-length 50

set-window-option -g window-status-current-style fg=colour166,bright

bind r source-file ~/.tmux.conf \; display "Tmux Reloaded"
