apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: dev-mongo
data:
  MONGO_URI: "mongodb://adminUser:112233@172.16.16.200:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.7"
